"""The site snippet for a town's own domain, and nothing else.

Setting a custom domain used to regenerate the entire Caddyfile from a template
in the request handler. Five things were wrong with that, and they compound:

  1. It proxied the frontend to `frontend:5173` -- the Vite *dev* server. The
     real config uses `frontend:80`, which is nginx. So a successful reload
     would have returned 502 for every page.

  2. It dropped the security header block. Content-Security-Policy, HSTS,
     X-Content-Type-Options and the `-Server` suppression all vanish, silently,
     on the day somebody sets a domain.

  3. It dropped `import /etc/caddy/tenants/*.caddy` and the orchestrator panel
     block, so every provisioned town tenancy disappears from the reverse proxy.

  4. It wrote to `PROJECT_ROOT/Caddyfile`, defaulting to `/project/Caddyfile`.
     Compose mounts the repository's `./Caddyfile` into the *caddy* container.
     The backend container has no such path, so the write failed or landed
     somewhere nothing reads.

  5. It then POSTed the config to `http://caddy:2019/load`. Caddy's admin
     endpoint listens on `localhost:2019` *inside its own container* unless
     told otherwise, and the shipped Caddyfile never told it otherwise -- so
     the reload was refused every time, which is the symptom: "Caddyfile saved
     but could not reload Caddy automatically."

The fix is to stop rewriting the main config. Caddy already imports a directory
of tenant snippets; a town's domain is one more snippet. The base file keeps
owning the headers, the tenants import and the panel, and a domain change adds
or replaces one small file that cannot damage any of it.

Pure, so the rendering is testable without Caddy, a filesystem, or a container.
"""

from __future__ import annotations

import re
from typing import Optional

# A hostname, and nothing that could be read as Caddy syntax.
#
# This string is written into a config file that a server parses and acts on.
# A value containing a brace, a newline or a space is not a domain -- it is an
# attempt to add a directive, and `reverse_proxy` to an arbitrary host is the
# obvious one to add.
_HOSTNAME = re.compile(
    r"^(?=.{1,253}$)(?!-)[A-Za-z0-9-]{1,63}(?<!-)"
    r"(?:\.(?!-)[A-Za-z0-9-]{1,63}(?<!-))+$"
)

# Snippet filename, inside the directory the base Caddyfile imports.
SNIPPET_NAME = "custom-domain.caddy"


class InvalidDomain(ValueError):
    """The value is not a hostname we will write into a server config."""


def normalise_domain(value: Optional[str]) -> str:
    """Trim, lowercase, strip a scheme and any path. Raise if it is not a host.

    Admins paste what is in their address bar, so `https://town.nj.gov/` is the
    common input and rejecting it outright would be pedantry. Anything that is
    still not a hostname after that is refused rather than escaped -- there is
    no legitimate domain containing a brace.
    """
    if not value:
        raise InvalidDomain("No domain given")

    candidate = value.strip().lower()
    candidate = re.sub(r"^[a-z]+://", "", candidate)
    candidate = candidate.split("/")[0].split("?")[0].strip()
    # A port is a deployment detail, not part of the certificate's name.
    candidate = candidate.split(":")[0]

    if candidate in ("localhost", ""):
        raise InvalidDomain("A public domain is needed for a certificate")
    if not _HOSTNAME.match(candidate):
        raise InvalidDomain(f"{value!r} is not a valid domain name")
    return candidate


def render_snippet(domain: str, *, backend: str = "backend:8000",
                   frontend: str = "frontend:80",
                   primary_domain: Optional[str] = None) -> str:
    """One site block for the town's domain.

    Deliberately mirrors the base file's routing, including the port. The
    previous version's `frontend:5173` is the Vite dev server; production runs
    nginx on 80, and getting this wrong turns a domain change into a site-wide
    502 that looks like a DNS problem.

    Headers are not repeated here. They live in a shared snippet the base file
    defines, so there is exactly one Content-Security-Policy in the deployment
    and this file cannot quietly ship a weaker one.
    """
    domain = normalise_domain(domain)
    if not primary_domain:
        import os
        primary_domain = os.environ.get("DOMAIN", "").strip()
    if primary_domain:
        try:
            if normalise_domain(primary_domain) == domain:
                return f"# Domain '{domain}' matches primary deployment domain in base Caddyfile.\n"
        except InvalidDomain:
            pass

    return (
        f"# Generated by Pinpoint when an administrator set the town's domain.\n"
        f"# Edited by hand? It will be overwritten the next time the domain is\n"
        f"# saved. Put durable changes in the base Caddyfile.\n"
        f"{domain} {{\n"
        f"    import pinpoint_site {backend} {frontend}\n"
        f"}}\n"
    )


def describe_reload(ok: bool, detail: str = "") -> dict:
    """What to tell an administrator, in terms they can act on.

    The old message ended "Please run: docker-compose restart caddy" whether or
    not that was the problem, and reported `status: partial` for a change that
    had in fact done nothing at all.
    """
    if ok:
        return {
            "reloaded": True,
            "message": "Caddy picked up the new domain. The certificate is "
                       "issued on the first request, which can take a few seconds.",
            "next_step": None,
        }
    return {
        "reloaded": False,
        "message": (
            "The domain is saved, but Caddy did not reload, so it is not "
            "serving that name yet." + (f" ({detail})" if detail else "")
        ),
        # Named exactly, because "restart caddy" is not a thing a clerk can be
        # expected to translate into a command on the right machine.
        "next_step": "docker compose restart caddy",
    }
