"""Add the road-geometry and blocked-request tables.

These three tables and their indexes existed only in the models. The app created
them with `Base.metadata.create_all` at startup, so deployments worked, but
Alembic's head did not describe them -- meaning `alembic upgrade head` against a
clean database produced a schema missing every one of them, and the two ways of
creating the schema disagreed about what it was.

This closes that gap so migrations are the single description of the schema.

Written by hand rather than autogenerated: no live database was reachable, and
`--autogenerate` against the wrong database is worse than reading the models.
The GIST index in particular is one autogenerate cannot express -- it indexes
the geography *cast* of the column, not the column.

Revision ID: e5f6a7b8c9d0
Revises: d4e5f6a7b8c9
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from geoalchemy2 import Geometry

revision: str = "e5f6a7b8c9d0"
down_revision: Union[str, None] = "d4e5f6a7b8c9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    existing = set(sa.inspect(bind).get_table_names())

    # Idempotent because every deployment that predates this migration already
    # has these tables from create_all. The baseline path in app/db/migrate.py
    # normally stamps those installs past this revision, but an operator who
    # runs `alembic upgrade head` by hand must not hit a duplicate-table error.
    if "road_segments" not in existing:
        op.create_table(
            "road_segments",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("source_id", sa.String(length=40), nullable=False),
            sa.Column("source_feature_id", sa.String(length=120), nullable=False),
            sa.Column("name", sa.String(length=255), nullable=True),
            sa.Column("name_norm", sa.String(length=255), nullable=True),
            sa.Column("ref", sa.String(length=80), nullable=True),
            sa.Column("ref_norm", sa.String(length=80), nullable=True),
            sa.Column("highway_class", sa.String(length=40), nullable=True),
            sa.Column("geom", Geometry(geometry_type="LINESTRING", srid=4326), nullable=False),
            sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
            sa.PrimaryKeyConstraint("id"),
        )

    if "road_data_status" not in existing:
        op.create_table(
            "road_data_status",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("state_code", sa.String(length=2), nullable=True),
            sa.Column("source_id", sa.String(length=40), nullable=True),
            sa.Column("source_name", sa.String(length=255), nullable=True),
            sa.Column("endpoint", sa.String(length=500), nullable=True),
            sa.Column("segment_count", sa.Integer(), nullable=True),
            sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("source_updated_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("consecutive_failures", sa.Integer(), nullable=True),
            sa.Column("last_error", sa.Text(), nullable=True),
            sa.Column("corridor_metres", sa.Integer(), nullable=True),
            sa.PrimaryKeyConstraint("id"),
        )

    if "blocked_request_log" not in existing:
        op.create_table(
            "blocked_request_log",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("service_code", sa.String(length=50), nullable=True),
            sa.Column("service_name", sa.String(length=255), nullable=True),
            sa.Column("jurisdiction_name", sa.String(length=255), nullable=True),
            sa.Column("road_name", sa.String(length=255), nullable=True),
            sa.Column("block_type", sa.String(length=20), nullable=True),
            sa.Column("lat", sa.Float(), nullable=True),
            sa.Column("long", sa.Float(), nullable=True),
            sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
            sa.PrimaryKeyConstraint("id"),
        )

    # IF NOT EXISTS throughout, for the same create_all-predates-this reason.
    #
    # The GIST index is on `(geom::geography)`, not on `geom`. Every distance
    # query casts to geography to get true metres, and an index on the bare
    # geometry column will not be used by a query on the cast -- Postgres treats
    # them as different expressions. Indexing the geometry instead is a silent
    # full scan on every road lookup, which only shows up as slowness once a
    # town has a few hundred thousand segments.
    # Written out one literal call at a time rather than looped over a tuple.
    # The startup classifier in app/db/migrate.py reads the SQL to decide
    # whether this revision may auto-apply, and it can only read literals -- a
    # loop variable makes the statement unknowable at scan time, which the
    # classifier correctly treats as "make a human look at it". Being explicit
    # here is what lets this migration run unattended.
    op.execute("CREATE INDEX IF NOT EXISTS ix_road_segments_geog "
               "ON road_segments USING GIST ((geom::geography))")
    op.execute("CREATE INDEX IF NOT EXISTS ix_road_segments_name_norm "
               "ON road_segments (name_norm)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_road_segments_ref_norm "
               "ON road_segments (ref_norm)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_road_segments_source_id "
               "ON road_segments (source_id)")
    op.execute("CREATE UNIQUE INDEX IF NOT EXISTS uq_road_segment_source "
               "ON road_segments (source_id, source_feature_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_blocked_log_created "
               "ON blocked_request_log (created_at)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_blocked_log_jurisdiction "
               "ON blocked_request_log (jurisdiction_name)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_blocked_log_service_code "
               "ON blocked_request_log (service_code)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_blocked_log_block_type "
               "ON blocked_request_log (block_type)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_blocked_log_road_name "
               "ON blocked_request_log (road_name)")


def downgrade() -> None:
    op.drop_table("blocked_request_log")
    op.drop_table("road_data_status")
    op.drop_table("road_segments")
